name: Build and Deploy

on:
  schedule:
    # Run at 8 AM UTC every weekday
    - cron: '0 8 * * 1-5'
  workflow_dispatch: # Allow manual triggers

env:
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate transcription
      env:
        GLADIA_API_KEY: ${{ secrets.GLADIA_API_KEY }}
        RSS_URL: ${{ secrets.RSS_URL }}
      run: npm run generate-transcription
    
    - name: Build Next.js app
      run: npm run build
    
    - name: Export static files
      run: npx next export
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
    
    - name: Commit transcription data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/latest.json public/audio/* public/transcriptions/* || true
        git commit -m "Update transcription data for $(date +'%Y-%m-%d')" || true
        git push || true